version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: web-app
    ports:
      - "8080:80"
    environment:
      - ENV=dev
    volumes:
      - ./nginx-logs:/var/log/nginx 
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  elasticsearch:
    image: elasticsearch:9.0.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - elk

  logstash:
    image: logstash:9.0.2
    container_name: logstash
    volumes:
      - ./logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ./nginx-logs:/var/log/nginx
    depends_on:
      - elasticsearch
    networks:
      - elk

  kibana:
    image: kibana:9.0.2
    container_name: kibana
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk

volumes:
  redis_data:
  es_data:

networks:
  elk:
    driver: bridge
