version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: web-app
    ports:
      - "8080:80"
    environment:
      - ENV=dev
    depends_on:
      - redis

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
