version: '3.8'

services:
  web:
    image: nginx:alpine
    container_name: web-app
    ports:
      - "8080:80"
    environment:
      - ENV=dev
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "wget -q -O /dev/null http://localhost:80/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./healthcheck.conf:/etc/nginx/conf.d/default.conf

  redis:
    image: redis:latest
    container_name: redis-server
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  redis_data:
